define BOGON_IP6 = [
  ::/8+,                         # RFC 4291 IPv4-compatible, loopback, et al
  0100::/64+,                    # RFC 6666 Discard-Only
  2001:2::/48+,                  # RFC 5180 BMWG
  2001:10::/28+,                 # RFC 4843 ORCHID
  2001:db8::/32+,                # RFC 3849 documentation
  3fff::/20+,                    # RFC 9637 documentation
  2002::/16+,                    # RFC 7526 6to4 anycast relay
  3ffe::/16+,                    # RFC 3701 old 6bone
  5f00::/16+,                    # RFC 9602 SRv6
  fc00::/7+,                     # RFC 4193 unique local unicast
  fe80::/10+,                    # RFC 4291 link local unicast
  fec0::/10+,                    # RFC 3879 old site local unicast
  ff00::/8+                      # RFC 4291 multicast
];

define BOGON_ASNS = [
  0,                      # RFC 7607
  23456,                  # RFC 4893 AS_TRANS
  64496..64511,           # RFC 5398 and documentation/example ASNs
  64512..65534,           # RFC 6996 Private ASNs
  65535,                  # RFC 7300 Last 16 bit ASN
  65536..65551,           # RFC 5398 and documentation/example ASNs
  65552..131071,          # RFC IANA reserved ASNs
  4200000000..4294967294, # RFC 6996 Private ASNs
  4294967295              # RFC 7300 Last 32 bit ASN
];

function drop_bogon_prefixes() {
  if net ~ BOGON_IP6 then reject;
}

function drop_bogon_asns() {
  if bgp_path ~ BOGON_ASNS then reject;
}
