function drop_rpki_invalid()
{
  case net.type {
    NET_IP4: {
      if roa_check(tab_roa4, net, bgp_path.first) = ROA_INVALID then {
        reject;
      }
    }
    NET_IP6: {
      if roa_check(tab_roa6, net, bgp_path.first) = ROA_INVALID then {
        reject;
      }
    }
  }
}
