define TRANSIT_ASNS = [
  174,                  # Cogent
  701,                  # UUNET
  1299,                 # Telia
  1239,                 # Sprint
  2914,                 # NTT Ltd.
  3257,                 # GTT Backbone
  3320,                 # Deutsche Telekom AG (DTAG)
  3356,                 # Level3
  3491,                 # PCCW
  4134,                 # Chinanet
  5511,                 # Orange
  6453,                 # Tata Communications
  6461,                 # Zayo Bandwidth
  6762,                 # Seabone / Telecom Italia
  6830,                 # Liberty Global
  7018,                 # AT&T
  6939,                 # Hurricane Electric
  12956                 # Telxius / Telefonica
];

function drop_transit_asns() {
  if bgp_path ~ TRANSIT_ASNS then reject;
}
