define ASN_FOGIXP = 47498;
define IP6_FOGIXP = 2001:7f8:ca:1::20:7118:1;

define ASN_FOGIXP_FRA = 61190;
define IP6_FOGIXP_FRA = 2001:7f8:11c:1::20:7118:1;
define IP4_FOGIXP_FRA = 185.0.30.83;

function fogixp() -> bool {
  ixp(ASN_FOGIXP);
  return true;
}

function fogixp_fra() -> bool {
  ixp(ASN_FOGIXP_FRA);
  return true;
}

template bgp fogixp6 from peer6 {
  source address IP6_FOGIXP;
  interface "eth1";

  default bgp_local_pref PEER;
}

template bgp fogixp_fra6 from peer6 {
  source address IP6_FOGIXP_FRA;
  interface "eth2";

  default bgp_local_pref PEER;
}

template bgp fogixp_fra4 from peer4 {
  source address IP4_FOGIXP_FRA;
  interface "eth2";

  default bgp_local_pref PEER;
}

include "fogixp/*.conf";
