protocol bgp up_lagrange from peer6 {
  neighbor 2a0f:85c2:7::38f as 209735;

  ipv6 {
    import where incoming(209735, TRANSIT);
    export where outgoing(209735, TRANSIT);
  };

  default bgp_local_pref TRANSIT;
  local role customer;

  multihop 2;
}
