protocol kernel k6 {
  scan time 10;

  ipv6 {
    table kernel6;

    import all;
    export all;
  };
}

protocol pipe k6_master {
  table master6;
  peer table kernel6;

  export filter {
    if source = RTS_STATIC
    then {
      krt_prefsrc = IP6_SELF;
      accept;
    }

    if source != RTS_BGP then reject;

    krt_prefsrc = IP6_SELF;

    reject;
  };

  import none;
}
