attribute int failed_rsec;

protocol kernel k6 {
  scan time 10;

  ipv6 {
    table kernel6;

    import all;
    export all;
  };
}

protocol pipe k6_master {
  table master6;
  peer table kernel6;

  export filter {
    if source = RTS_STATIC
    then {
      krt_prefsrc = IP6_SELF;
      accept;
    }

    if source != RTS_BGP then reject;

    if dest = RTD_UNREACHABLE then {
      if failed_rsec > 0
        then accept;
        else reject;
    }

    krt_prefsrc = IP6_SELF;

    int src_type = bgp_large_community.filter([(ASN_SELF, INFO_SOURCE, *)]).max.data2;

    if src_type !~ [SELF, DOWN] then reject;

    accept;
  };

  import none;
}
