protocol bgp fogixp_valve6 from fogixp_fra6 {
  neighbor 2001:7f8:11c:1::3:2590:1 as 32590;

  ipv6 {
    import where incoming(32590, PEER) && fogixp_fra();
    export where outgoing(32590, PEER);
  };
}

protocol bgp fogixp_valve4 from fogixp_fra4 {
  neighbor 185.0.30.31 as 32590;

  ipv4 {
    import where incoming(32590, PEER) && fogixp_fra();
    export where outgoing(32590, PEER);
  };
}

protocol bgp fogixp_cf6 from fogixp_fra6 {
  neighbor 2001:7f8:11c:1:0:1:3335:1 as 13335;

  ipv6 {
    import where incoming(13335, PEER) && fogixp_fra();
    export where outgoing(13335, PEER);
  };
}

protocol bgp fogixp_cf4 from fogixp_fra4 {
  neighbor 185.0.30.33 as 13335;

  ipv4 {
    import where incoming(13335, PEER) && fogixp_fra();
    export where outgoing(13335, PEER);
  };
}
