protocol bgp rs_fogixp1 from fogixp6 {
  neighbor 2001:7f8:ca:1::111 as ASN_FOGIXP;

  ipv6 {
    import where incoming(ASN_FOGIXP, RS) && fogixp();
    export where outgoing(ASN_FOGIXP, RS);
  };

  default bgp_local_pref RS;
  local role rs_client;
}

protocol bgp rs_fogixp2 from fogixp6 {
  neighbor 2001:7f8:ca:1::222 as ASN_FOGIXP;

  ipv6 {
    import where incoming(ASN_FOGIXP, RS) && fogixp();
    export where outgoing(ASN_FOGIXP, RS);
  };

  default bgp_local_pref RS;
  local role rs_client;
}
