protocol bgp rs_onix1 from onix6 {
  neighbor 2001:504:125:e1::1 as ASN_ONIX;

  ipv6 {
    import where incoming(ASN_ONIX, RS) && onix();
    export where outgoing(ASN_ONIX, RS);
  };

  default bgp_local_pref RS;
  local role rs_client;
}

protocol bgp rs_onix2 from onix6 {
  neighbor 2001:504:125:e1::2 as ASN_ONIX;

  ipv6 {
    import where incoming(ASN_ONIX, RS) && onix();
    export where outgoing(ASN_ONIX, RS);
  };

  default bgp_local_pref RS;
  local role rs_client;
}
