protocol bgp up_he from onix6 {
  neighbor 2001:504:125:e1::3 as 6939;

  ipv6 {
    import where incoming(6939, TRANSIT) && onix();
    export where outgoing(6939, TRANSIT);
  };

  default bgp_local_pref TRANSIT;
  local role customer;
}
