define ASN_ONIX = 57369;
define IP6_ONIX = 2001:504:125:e1::153;

function onix() -> bool {
  ixp(ASN_ONIX);
  return true;
}

template bgp onix6 from peer6 {
  source address IP6_ONIX;

  default bgp_local_pref PEER;
}

include "onix/*.conf";
