protocol bgp up_gocodeit from peer6 {
  neighbor 2602:fd50:100::5 as 835;

  ipv6 {
    import where incoming(835, TRANSIT);
    export where outgoing(835, TRANSIT);
  };

  default bgp_local_pref TRANSIT;
  local role customer;

  multihop 3;
}

protocol bgp up4_gocodeit from peer4 {
  neighbor 170.39.230.5 as 835;

  ipv4 {
    import where incoming(835, TRANSIT);
    export where outgoing(835, TRANSIT);
  };

  default bgp_local_pref TRANSIT;
  local role customer;

  multihop 3;
}
