template bgp bgp6 {
  local as ASN_SELF;

  ipv6 {
    igp table local6;
  };

  graceful restart on;
}

template bgp bgp4 {
  local as ASN_SELF;

  ipv4 {
    igp table local4;
  };

  graceful restart on;
}
