template bgp peer_bgptools from bgp_mp {
  source address IP6_HOST;
  neighbor as 212232;

  ipv4 {
    add paths tx;
    import where incoming(212232, PEER);
    export where outgoing(212232, DOWN);
  };

  ipv6 {
    add paths tx;
    import where incoming(212232, PEER);
    export where outgoing(212232, DOWN);
  };

  local role provider;

  multihop 255;
}
