template bgp peer6_monitoring from bgp6 {
  source address IP6_HOST;
  neighbor as 212232;

  ipv6 {
    add paths tx;
    import where incoming(212232);
    export where outgoing(212232);
  };

  local role provider;

  multihop 255;
}
