template bgp peer6 from bgp6 {
  source address IP6_HOST;

  ipv6;

  local role peer;

  hold time 600;
}

template bgp peer4 from bgp4 {
  source address IP4_HOST;

  ipv4;

  local role peer;

  hold time 600;
}
