protocol bgp bgp_tools from peer6_monitoring {
  neighbor 2a0c:2f07:9459::b19;
}

# TODO: also make a template for HE
protocol bgp bgp_he from bgp6 {
  source address IP6_HOST;
  neighbor 2600:7000:1000::13	as 393338;

  ipv6 {
    add paths tx;
    import where incoming(393338);
    export where outgoing(393338);
  };

  local role provider;

  multihop 255;
}
