define ASN_PDX = 52025;
define IP6_PDX = 2602:fa7e:21::1;

protocol bgp up_pdx from peer6 {
  neighbor IP6_PDX as ASN_PDX;
  source address IP6_HOST;

  ipv6 {
    next hop self;
    import where incoming(ASN_PDX, TRANSIT);
    export where outgoing(ASN_PDX, TRANSIT);
  };

  default bgp_local_pref TRANSIT;
  local role customer;

  multihop;
}
