protocol static r6_export {
  ipv6;

  route 2a14:6f44:11::/48 blackhole;
  route 2a14:6f44:1e::/48 reject;
}

protocol static r6_local {
  ipv6 { table local6; };

  route 2602:fd50:100::/40 via "eth0";
}
