function outgoing(int dst_asn; int dst_type) -> bool {
  apply_filters();

  if proto = "r6_export" || proto = "r4_export"
    then mark(INFO_SOURCE, SELF);

  int src_type = bgp_large_community.filter([(ASN_SELF, INFO_SOURCE, *)]).max.data2;

  if dst_type = DOWN
    then return true;

  if src_type ~ [SELF, DOWN]
    then return true;
    else return false;
}
